### ISSUE TITLE
PhonegapBuild gives build error 

### ISSUE THREAD

**Issue by mauron85** [mauron85/cordova-plugin-mauron85-background-geolocation-phonegapbuild#1]
The -phonegapbuild version of the plugin, does not build with cradle,
maybe some incompatibility with one of the other plugins?

My configured plug-ins:

  &lt;gap:plugin name="cordova-plugin-battery-status" version="1.1.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-camera" version="1.2.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-file" version="3.0.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-device" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-geolocation" version="1.0.1" source="npm" /&gt;

  &lt;gap:plugin name="cordova-plugin-inappbrowser" version="1.0.1" source="npm"/&gt;
  &lt;gap:plugin name="cordova-plugin-splashscreen" version="2.1.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-media" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-network-information" version="1.0.1" source="npm" /&gt;

  &lt;gap:plugin name="phonegap-plugin-barcodescanner" version="4.1.0" source="npm" /&gt;

  &lt;!--Temperary only iOS, see issue: http://community.phonegap.com/nitobi/topics/cordova-plugin-push-notification-failed-with-gradle-android?rfm=1 --&gt;
  &lt;gap:plugin name="cordova-plugin-push-notification" version="2.5.2" source="npm" gap:platform="ios" /&gt;
  &lt;gap:plugin name="cordova-plugin-statusbar" version="1.0.1" source="npm" /&gt;

  &lt;gap:plugin name="cordova-plugin-powermanagement" version="1.0.1" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-whitelist" version="1.0.0" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" version="0.7.3" source="npm" /&gt;
  &lt;gap:plugin name="cordova-plugin-keyboard" version="1.1.2" source="npm" /&gt;

My other settings:
  &lt;gap:platform name="android" /&gt;
  &lt;preference name="webviewbounce" value="false" /&gt;
  &lt;preference name="phonegap-version" value="cli-5.2.0" /&gt;
  &lt;preference name="detect-data-types" value="false" /&gt;
  &lt;preference name="stay-in-webview" value="false" /&gt;
  &lt;preference name="exit-on-suspend" value="false" /&gt;
  &lt;preference name="KeepRunning" value="true" /&gt;
  &lt;preference name="android-windowSoftInputMode" value="adjustPan" /&gt;
  &lt;preference name="KeyboardShrinksView" value="false" /&gt;
  &lt;preference name="orientation" value="both" /&gt;
  &lt;preference name="show-splash-screen-spinner" value="false" /&gt;
  &lt;preference name="auto-hide-splash-screen" value="false" /&gt;
  &lt;preference name="splash-screen-duration" value="2500" /&gt;
  &lt;preference name="fullscreen" value="true" /&gt;
  &lt;preference name="prerendered-icon" value="true" /&gt;
  &lt;preference name="load-url-timeout" value="75000" /&gt;
  &lt;preference name="android-build-tool" value="gradle" /&gt;
  &lt;preference name="StatusBarOverlaysWebView" value="false" /&gt;
  &lt;preference name="BackupWebStorage" value="cloud"/&gt;
  &lt;preference name="KeyboardDisplayRequiresUserAction" value="false"/&gt;
  &lt;preference name="SuppressesIncrementalRendering" value="true"/&gt;
  &lt;gap:config-file platform="android" parent="/manifest/application"&gt;
    &lt;activity android:launchMode="singleTop" /&gt;
  &lt;/gap:config-file&gt;

Phonegap build log:
## Build Date: 2015-11-26 14:46:14 +0000

Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true -x lintVitalRelease
:preBuild
:compileReleaseNdk
:preReleaseBuild
:checkReleaseManifest
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preBuild
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResourceswarning: string 'menu_settings' has no default translation.

:generateReleaseSources
:compileReleaseJava/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:14: error: package android.support.v4.app does not exist
import android.support.v4.app.NotificationCompat;
                             ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                                                          ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:120: error: package NotificationCompat does not exist
    protected NotificationCompat.Builder setClickEvent (NotificationCompat.Builder builder) {
                                ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                              ^
/project/src/com/tenforwardconsulting/cordova/bgloc/AbstractLocationService.java:88: error: package NotificationCompat does not exist
            NotificationCompat.Builder builder = new NotificationCompat.Builder(this);
                                                                       ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileReleaseJava'.
  &gt; Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.219 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true,-x,lintVitalRelease

**Comment by mauron85** [comment]
@renevaessen: You're probably missing Android Support Library. Check Android SDK Manager

**Comment by genXdev** [comment]
Is that another plugin, or something I can configure in my config.xml for PhoneGap Build?

**Comment by mauron85** [comment]
Yes, read https://github.com/mauron85/cordova-plugin-mauron85-background-geolocation-phonegapbuild#registering-plugin-for-adobe-phonegap-build

**Comment by ahlidap** [comment]
Yep,

This isn't working with PhonegapBuild :(

addind the following line to config.xml

```
<gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" source="npm"/>
```

will result in build error.

```
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: RegistrationIntentService.java - You can fix this here
```

using cli -5.2.0 and gradle.

Builds perfectly without this plugin (in fact I have the facebook connect plugin which is gradle sensitive)

**Comment by mauron85** [comment]
This repo is awfully behind cordova-plugin-mauron85-background-geolocation. I will merge latest changes from it. Anyway, can you post whole build error. From what have you posted it's not clear why this plugin is not working.

Specially this formulations have no sense to me.:

"Some official plugins" - this is not official plugin
"RegistrationIntentService.java" - not referencing this anywhere in plugin

**Comment by mauron85** [comment]
@ahlidap Please try new release 0.9.4 (already on npm)

**Comment by ahlidap** [comment]
@mauron85 ,

I can't get it to work.
I've removed all my plugins one by one until only remain:

```
<gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" source="npm"/>
```

And I got this from PGB:

```
Build Date: 2016-02-03 14:51:19 +0000
Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true
:preBuild
:preReleaseBuild
:checkReleaseManifest
:preDebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV42310Library
:prepareComGoogleAndroidGmsPlayServicesBase810Library
:prepareComGoogleAndroidGmsPlayServicesBasement810Library
:prepareComGoogleAndroidGmsPlayServicesLocation810Library
:prepareComGoogleAndroidGmsPlayServicesMaps810Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources/project/res/drawable-hdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-xhdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaNote: /project/src/com/tenforwardconsulting/cordova/bgloc/BackgroundGeolocationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/com/tenforwardconsulting/cordova/bgloc/FusedLocationService.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:lintVitalRelease
:compileReleaseNdk
:preDexRelease
:dexRelease
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexRelease'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
    /android-sdk/build-tools/23.0.1/dx --dex --output /project/build/intermediates/dex/release --input-list=/project/build/intermediates/tmp/dex/release/inputList.txt
  Error Code:
    2
  Output:

    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)



* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 56.746 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true
```

And the build with all my plugins including this one:

```
Build Date: 2016-02-03 14:57:26 +0000
Running: /project/gradlew cdvBuildRelease -b /project/build.gradle -Dorg.gradle.daemon=true
:preBuild
:preReleaseBuild
:checkReleaseManifest
:preDebugBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportCardviewV72310Library
:prepareComAndroidSupportMultidex101Library
:prepareComAndroidSupportSupportV132310Library
:prepareComAndroidSupportSupportV42310Library
:prepareComFacebookAndroidFacebookAndroidSdk490Library
:prepareComGoogleAndroidGmsPlayServicesBase810Library
:prepareComGoogleAndroidGmsPlayServicesBasement810Library
:prepareComGoogleAndroidGmsPlayServicesGcm810Library
:prepareComGoogleAndroidGmsPlayServicesLocation810Library
:prepareComGoogleAndroidGmsPlayServicesMaps810Library
:prepareProjectCordovaLibUnspecifiedReleaseLibrary
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources/project/res/drawable-xhdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-ldpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-hdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-mdpi/icon.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJava/project/src/com/adobe/phonegap/push/RegistrationIntentService.java:30: error: cannot find symbol
                    GoogleCloudMessaging.INSTANCE_ID_SCOPE, null);
                                        ^
  symbol:   variable INSTANCE_ID_SCOPE
  location: class GoogleCloudMessaging
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.686 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildRelease,-b,/project/build.gradle,-Dorg.gradle.daemon=true
```

As it complains about "GoogleCloudMessaging" I've started to remove the push plugin and so on.... but can't get it to build.

The big thing of your version is that they will execute JS code and not just the ajax post which is great!
If you have any hint please tell me.
I will keep trying to build my app with it.

Thanks

**Comment by mauron85** [comment]
Can you provide list of your plugins and versions?

**Comment by ahlidap** [comment]
Hi @mauron85 , sure, here it is:

```
cordova-plugin-mauron85-background-geolocation-phonegapbuild    |npm|0.9.4
phonegap-plugin-push            |npm|1.5.2

cordova-plugin-facebook4    |npm|1.3.0
cordova-plugin-whitelist    |npm|1.2.0
cordova-plugin-x-socialsharing  |npm|5.0.7


com.dileep.plugins.datepicker   |pgb|0.0.1
net.tunts.webintent         |pgb|0.2.1
nl.x-services.plugins.toast |pgb|2.0.2
org.apache.cordova.contacts |pgb|0.2.16
org.apache.cordova.device       |pgb|0.3.0
org.apache.cordova.device-orientation   |pbg|0.3.11
org.apache.cordova.dialogs  pgb|0.2.10
org.apache.cordova.inappbrowser pgb|0.6.0
org.apache.cordova.network-information  |pgb|0.2.15
```

**Comment by ahlidap** [comment]
@mauron85 ,

I've created a fork of your repo and managed to get my app to compile on PGB by removing the following dependency line on plugin.xml

```
<dependency id="cordova-plugin-googleplayservices" />
```

I assume this only works for me as I have other plugin that have that dependency (or something related to it)

I don't know if there is some other way (new one) to declare such dependency (haven't look the other plugins yet)

By the way, is there any way (trick?) to get rid of that notification on status bar?
The idea of my app is: The user will receive a notification if it enters on certain area,
It works, but that notification always there is annoying. Tther apps like FourSquare don't have such notification always present.

**Comment by Nett** [comment]
Hello, @mauron85 

I use your plugin, and it's really good. But now I faced with the same issue.
I also use push plugin: https://github.com/phonegap/phonegap-plugin-push
< plugin name="phonegap-plugin-push" source="npm" />
And it requires:
< preference name="android-build-tool" value="gradle" />

This is how I include your plugin:
< gap:plugin name="cordova-plugin-mauron85-background-geolocation-phonegapbuild" source="npm"/>

If I remove GEO-Location plugin, build finishes successfully.
But I need your plugin and push plugin in my application.

Here is build log:

## Build Date: 2016-02-29 13:17:12 +0000

## PLUGIN OUTPUT

Installing "org.apache.cordova.device@0.2.12" for android
Installing "de.appplant.cordova.plugin.background-mode@0.6.4" for android
Fetching plugin "cordova-plugin-console" via npm
Installing "cordova-plugin-console@1.0.2" for android
Fetching plugin "cordova-plugin-device" via npm
cordova-plugin-device" will not install due to "/project/cordova/plugins/org.apache.cordova.device" being installed.
Plugin "org.apache.cordova.device" already installed on android.
Fetching plugin "cordova-plugin-network-information" via npm
Installing "cordova-plugin-network-information@1.2.0" for android
Fetching plugin "cordova-plugin-dialogs" via npm
Installing "cordova-plugin-dialogs@1.2.0" for android
Fetching plugin "cordova-plugin-vibration" via npm
Installing "cordova-plugin-vibration@2.1.0" for android
Fetching plugin "cordova-plugin-whitelist" via npm
Installing "cordova-plugin-whitelist@1.2.1" for android

```
           This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
```

Fetching plugin "phonegap-plugin-push" via npm
Installing "phonegap-plugin-push@1.5.3" for android
Fetching plugin "cordova-plugin-mauron85-background-geolocation-phonegapbuild" via npm
Installing "cordova-plugin-mauron85-background-geolocation-phonegapbuild@0.9.4" for android
Fetching plugin "cordova-plugin-googleplayservices" via npm

## Installing "cordova-plugin-googleplayservices@19.0.3" for android

## COMPILE OUTPUT

Running: /project/gradlew cdvBuildDebug -b /project/build.gradle -Dorg.gradle.daemon=true
:preBuild
:compileDebugNdk
:preDebugBuild
:checkDebugManifest
:preReleaseBuild
:CordovaLib:compileLint
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:preBuild
:CordovaLib:preDebugBuild
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:packageDebugJar
:CordovaLib:compileDebugNdk
:CordovaLib:packageDebugJniLibs UP-TO-DATE
:CordovaLib:packageDebugLocalJar UP-TO-DATE
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:bundleDebug
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:preReleaseBuild
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseAidl
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:packageReleaseJar
:CordovaLib:compileReleaseNdk
:CordovaLib:packageReleaseJniLibs UP-TO-DATE
:CordovaLib:packageReleaseLocalJar UP-TO-DATE
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:bundleRelease
:prepareComAndroidSupportSupportV132310Library
:prepareComAndroidSupportSupportV42310Library
:prepareComGoogleAndroidGmsPlayServicesBase840Library
:prepareComGoogleAndroidGmsPlayServicesBasement840Library
:prepareComGoogleAndroidGmsPlayServicesGcm840Library
:prepareComGoogleAndroidGmsPlayServicesLocation840Library
:prepareComGoogleAndroidGmsPlayServicesMaps840Library
:prepareComGoogleAndroidGmsPlayServicesMeasurement840Library
:prepareProjectCordovaLibUnspecifiedDebugLibrary
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources/project/res/drawable-port-xxhdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-land-xxhdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
/project/res/drawable-port-xhdpi/splash.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

:processDebugManifest
:processDebugResourcesWarning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

:generateDebugSources
:compileDebugJavaNote: /project/src/com/tenforwardconsulting/cordova/bgloc/BackgroundGeolocationPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

:preDexDebug
:dexDebug
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
    at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
    at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
    at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
    at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
    at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
    at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
    at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
    at com.android.dx.command.dexer.Main.run(Main.java:277)
    at com.android.dx.command.dexer.Main.main(Main.java:245)
    at com.android.dx.command.Main.main(Main.java:106)

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexDebug'.
  
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  > /android-sdk/build-tools/23.0.1/dx --dex --no-optimize --output /project/build/intermediates/dex/debug --input-list=/project/build/intermediates/tmp/dex/debug/inputList.txt
  > Error Code:
  >   2
  > Output:
  
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/actions/ReserveIntents;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 0.305 secs

/project/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /project/gradlew with args: cdvBuildDebug,-b,/project/build.gradle,-Dorg.gradle.daemon=true

Could you please suggest something? How to clarify this issue?
Thank you!
